import { Inter } from "next/font/google";
import Timer from "@/components/header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Timer />
      <body className={inter.className}>{children}</body>
    </div>
  );
}
